"""Example: create a draft merge request using GitLab API."""

from datetime import datetime

from codesight.gitlab_client import GitLabClient


def main() -> None:
    gitlab = GitLabClient()

    branch_name = f"codesight/fixes-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
    gitlab.create_branch(branch_name=branch_name, ref="main")

    # In real usage, commit updated files before opening MR.
    mr = gitlab.create_merge_request(
        source_branch=branch_name,
        target_branch="main",
        title="CodeSight automated fixes",
        description="This draft MR contains AI-suggested fixes generated by CodeSight.",
        draft=True,
    )

    print("Created MR:", mr.get("web_url"))


if __name__ == "__main__":
    main()
